# Generated by Django 2.2.13 on 2021-04-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profesion_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesion',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='Adjuntos'),
        ),
    ]
